# Generated by Django 3.2.7 on 2021-09-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(blank=True, max_length=999999)),
                ('clicks', models.BigIntegerField(blank=True)),
                ('cost', models.FloatField(max_length=999999.99)),
            ],
        ),
    ]
