# Generated by Django 3.2.7 on 2021-09-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='views',
            field=models.IntegerField(blank=True),
        ),
    ]
