# Generated by Django 3.2.7 on 2021-09-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_alter_stats_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='clicks',
            field=models.BigIntegerField(blank=True, verbose_name='Клики'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='cost',
            field=models.FloatField(max_length=999999.99, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='views',
            field=models.IntegerField(blank=True, verbose_name='Просмотры'),
        ),
    ]
