# Generated by Django 3.2.7 on 2021-09-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20210924_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='cpc',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stats',
            name='cpm',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stats',
            name='date',
            field=models.DateTimeField(blank=True, verbose_name='Дата'),
        ),
    ]
