# Generated by Django 3.2.7 on 2021-09-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20210925_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='clicks',
            field=models.IntegerField(blank=True, verbose_name='Клики'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='cpc',
            field=models.FloatField(max_length=999999.99),
        ),
        migrations.AlterField(
            model_name='stats',
            name='cpm',
            field=models.FloatField(max_length=999999.99),
        ),
    ]
